compressionLevel: mixed

enableGlobalCache: false

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

npmPublishRegistry: "https://registry.npmjs.org/"

packageExtensions:
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/react-accordion@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-alert@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-avatar@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-checkbox@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-combobox@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-comboxbox@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-components@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-context-selector@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-dialog@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-drawer@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-field@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-infobutton@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-infolabel@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-input@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-menu@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-overflow@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-persona@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-popover@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-progress@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-radio@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-search@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-select@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-skeleton@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-slider@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-spinbutton@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-swatch-picker@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-swatch@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-switch@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-table@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-tabs@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-tag-picker@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-tags@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-teaching-popover@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-teaching-profile@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-textarea@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-toolbar@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/react-tree@*":
    peerDependencies:
      scheduler: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      react: "*"
  "@fluentui/theme@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@jest/reporters@*":
    dependencies:
      "@types/istanbul-lib-coverage": 2.0.3
  "@storybook/addon-controls@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      webpack: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      "@storybook/react-webpack5": "*"
      webpack: "*"
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      "@storybook/react-webpack5":
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      webpack: "*"
    peerDependenciesMeta:
      "@storybook/react-webpack5":
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  "@storybook/addon-interactions@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      webpack: "*"
  "@storybook/blocks@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/builder-manager@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/builder-webpack5@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/cli@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/core-common@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      webpack: ">= 5"
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  "@storybook/core-server@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/core-webpack@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      react: "*"
      react-dom: "*"
  "@storybook/instrumenter@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/preset-react-webpack@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/react-webpack5@*":
    peerDependencies:
      webpack: "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/store@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/telemetry@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      react: "*"
      react-dom: "*"
    peerDependenciesMeta:
      "@storybook/react-webpack5":
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      "@types/tapable": ^1.0.6
  storybook@*:
    peerDependencies:
      "@storybook/react-webpack5": "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
