npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@jest/reporters@*":
    dependencies:
      "@types/istanbul-lib-coverage": 2.0.3
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      "@types/tapable": ^1.0.6
  "@storybook/store@*":
    peerDependenciesMeta:
      react: { optional: true }
      react-dom: { optional: true }
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      "webpack": "*"
      "@storybook/react-webpack5": "*"
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      "webpack":
        optional: true
      "@storybook/react-webpack5":
        optional: true
      react-dom:
        optional: true
  vite-tsconfig-paths@*:
    peerDependencies:
      vite: "*"
  "@storybook/core-common@*":
    peerDependenciesMeta:
      react: { optional: true }
      react-dom: { optional: true }
      webpack: { optional: true }
    peerDependencies:
      "@storybook/react-webpack5": "*"
      "webpack": ">= 5"
  "@fluentui/theme@*":
    peerDependenciesMeta:
      '@types/react': { optional: true }
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      '@types/react': { optional: true }
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      react: "*"
  "@storybook/telemetry@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "@storybook/react-webpack5": "*"
    peerDependenciesMeta:
      "react":
        optional: true
      "react-dom":
        optional: true
      "@storybook/react-webpack5":
        optional: true
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      "webpack": "*"
    peerDependenciesMeta:
      "@storybook/react-webpack5":
        optional: true
      "webpack":
        optional: true
      react-dom:
        optional: true
  "@storybook/addon-interactions@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      "webpack": "*"
  "@storybook/addon-controls@*":
    peerDependencies:
      "webpack": "*"
      "@storybook/react-webpack5": "*"
  "@storybook/instrumenter@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "@storybook/react-webpack5": "*"
  "@storybook/builder-manager@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/builder-webpack5@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/blocks@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/preset-react-webpack@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/cli@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/core-server@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/core-webpack@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "storybook@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/api@*":
    peerDependencies:
      react: "*"
      "react-dom": "*"
  "@storybook/react-webpack5@*":
    peerDependencies:
      "webpack": "*"
  "@thematic/fluent@*":
    peerDependencies:
      styled-components: "*"


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
