npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@jest/reporters@*":
    dependencies:
      "@types/istanbul-lib-coverage": 2.0.3
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      "@types/tapable": ^1.0.6
  "@storybook/store@*": 
    peerDependenciesMeta:
      react: { optional: true }
      react-dom: { optional: true }
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
  vite-tsconfig-paths@*: 
    peerDependencies:
      vite: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
