name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - run: echo "actor is ${{github.actor}}"
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v1

      - run: yarn version check
        if: "github.actor != 'dependabot[bot]' && !contains(github.ref , 'release/') && !contains(github.head_ref , 'release/')"
        name: Version Check

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      #
      # Explicitly update the lockfile when processing a dependabot update
      #
      - run: yarn update-lockfile
        if: "github.actor == 'dependabot[bot]'"
        name: Update Yarn Lockfile

      - run: yarn install
        name: Install Dependencies

      - run: yarn ci
        name: Execute Tests

      #
      # Verify a clean repo; expected to fail for dependabot
      #
      - run: yarn git_is_clean
        if: "github.actor != 'dependabot[bot]'"
        name: Git is clean

      - name: Publish coverage to codecov.io
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  auto-merge:
    name: Auto-Merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    needs:
      - build
    steps:
      - name: auto-merge
        if: github.actor == 'dependabot[bot]'
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_PAT }}
