name: CI
on: [push, pull_request]
jobs:
  update-lockfile: 
    runs-on: ubuntu-latest
    if: "github.actor == 'dependabot[bot]'"
    strategy: 
      matrix: 
        node-version: [16.x]
    env:
      HUSKY: 0
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --no-immutable --mode=update-lockfile
      - run: yarn dedupe --mode=update-lockfile
      - name: git add yarn.lock && git commit
        run: |
          git config --global user.name 'darthtrevino'
          git config --global user.email 'darthtrevino@users.noreply.github.com'
          git add yarn.lock
          git commit -m 'build: fix yarn.lock [dependabot skip]'
          git push

  version-check: 
    runs-on: ubuntu-latest
    if: "!contains(github.ref , 'release/') && !contains(github.head_ref , 'release/') && !contains(github.ref , 'dependabot/') && !contains(github.head_ref , 'dependabot/')"
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn version check

  build:
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - run: echo "actor is ${{github.actor}}, ref is ${{github.ref}} head_ref is ${{github.head_ref}}"
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn ci
      - run: yarn git_is_clean
        if: "github.actor != 'dependabot[bot]'"
        name: Git is clean

      - name: Publish coverage to codecov.io
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  auto-merge:
    name: Auto-Merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    needs:
      - build
    steps:
      - name: auto-merge
        if: github.actor == 'dependabot[bot]'
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_PAT }}
