name: Version Check
on: [push, pull_request]
env:
  DEFAULT_NODE_VERSION: 16
jobs:
  version-check:
    runs-on: ubuntu-latest
    if: "!contains(github.ref , 'release/') && !contains(github.head_ref , 'release/') && !contains(github.ref , 'dependabot/') && !contains(github.head_ref , 'dependabot/')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.DEFAULT_NODE_VERSION}}
      - run: yarn version check
